subinclude("///ts//build_defs:ts")

ts_library(
    name = "layers",
    package = "@stack/layers",
    srcs = ["index.ts"],
    tsconfig_deps = ["//:tsconfig.json"],
    visibility = ["//test/..."],
)
